### ISSUE TITLE
Ability to upload image/s at the mission level

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#13]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
The ability to upload images (maps / coord diagrams etc) for missions in the same way they can be uploaded in the Campaign area.

**Describe alternatives you've considered**
-Baking images into mission briefing on MIZ.
-Posting Photocopies to people.

**Additional context**
Nil.

**Comment by jvanlint** [comment]
Mission imagery now available at the bottom of the mission detail screen.
