### ISSUE TITLE
Flight Tasks need to be visible in mission card.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#14]
**Is your feature request related to a problem? Please describe.**
Currently it is not clear from the Mission Card what a given flight is doing (Strike/CAP/BAI/BDA/SEAD etc). This will make it difficult to determine who to contact for what, (ie, who do I ask for escort?)

**Describe the solution you'd like**
Within the Mission Card under 'flights' the columns should be 'Callsign /  **Task** / Freq / AC Type / AC# / PACKAGE. 
Alternatively, the 'Callsign' column is amended to 'Callsign (Task)' and would read 'KNIFE (CAP)'.
This should be entered as a discrete value in the [Create/Edit Flight Page](https://apps.deadfrogstudios.com/airops/flight/update/25?returnUrl=/airops/flight/25/)

**Describe alternatives you've considered**
It could be achieved by manually typing 'KNIFE (CAP)' in the Callsign field, but this then muddles the Callsign of the flight if it is required pure elsewhere.

**Additional context**
Nil

**Comment by jvanlint** [comment]
Added Task table to hold all values for Tasks. Added Task as a element of the Flight object. Ammended Package and Flight screens to display the task for the flight. Fixed the mission card to also show Flight name with task in brackets after the name.
