### ISSUE TITLE
Cannot add targets to flight

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#20]
**Describe the bug**
It appears that targets can no longer be assigned to flights.

**To Reproduce**
1. Ensure target is loaded in mission
2. Navigate to flight screen
3. There is no blue " + Add Target " Button.
4. Wail hysterically.

**Expected behavior**
You should be able to add targets to a flight.

**Screenshots**
![20210518_205137](https://user-images.githubusercontent.com/40154322/118641255-42d8d100-b81d-11eb-9514-7df48d196510.jpg)

**Comment by jvanlint** [comment]
The entire target list is defined at a Mission level and then at the Flight level, targets are selected from the master list in the Edit Flight interface. Adding a +Add Target button here would imply adding a new target but in fact we allocating targets to flights from the master list defined at the mission level.

Edit the flight info to see a list of targets you can assign to a flight.

**Comment by Floydii** [comment]
So every target in the whole mission shows up on every flight's mission card?

**Comment by Steveveepee** [comment]
No, the targets in the flight's mission show up in their mission card.

**Comment by Floydii** [comment]
This may be a factor of Mobile vs Desktop. On mobile (most recently) you can go into edit the flight and select targets via checkbox. However, as of 19May21 the PC  version would simply display a list of targets with no clear way to select them.

**Comment by jvanlint** [comment]
The PC version should let you select multiple targets by Ctrl-Clicking (or Option-Clicking on Mac) to select multiple values. Please advise if this does not work for you.
