### ISSUE TITLE
Add 'Training' as a flight task

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#21]
**Describe the solution you'd like**
Add training as a selectable task for a flight.

**Describe alternatives you've considered**
Lying to flight members.

**Additional context**
![20210518_204038](https://user-images.githubusercontent.com/40154322/118641675-c7c3ea80-b81d-11eb-84b6-14fdef5e80f9.jpg)

**Comment by jvanlint** [comment]
New flight tasks can be added to the table using the Admin interface. Training has been added but these can be added or changed by anyone with admin privileges.

**Comment by Floydii** [comment]
Which option is it to edit tasks?
![Uploading 20210520_064443.jpg…]()

**Comment by jvanlint** [comment]
You need to click on "Admin" in your toolbar up top. Then look for the Tasks table on the left hand. This is considered a "reference" table and therefore I don't want to give any user the rights to add and delete values. Only "admin" types.
