### ISSUE TITLE
Waypoints not appearing in new missions Mission Card.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#22]
**Describe the bug**
New missions don't output flight waypoints on mission cards. Generating mission cards for older missions gives waypoints, but any changes are not reflected.

**To Reproduce**
1. Add waypoints to the flight
2. Produce mission card
3. Witness that there were no waypoints in the card
4. Wail uncontrollably.

**Expected behavior**
Waypoints and associated changes should appear on when next mission card is produced.

**Screenshots**

**Additional context**
Potentially this is an update rate issue (changes don't reflect for and hour or more after making them).

**Comment by Floydii** [comment]
Looking further into this, I think it's a mobile vs PC issue.

**Comment by Steveveepee** [comment]
Unable to reproduce on PC.
