### ISSUE TITLE
No field for player name support assets on mission card

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#23]
**Describe the bug**
It does not appear  that a players name appears when added against a support asset (GCI,AWACS etc)

**To Reproduce**
1. Add player name in designated field under 'support(s).
2. Produce mission card
3. Note no player name in supports section of mission card
4. Wail uncontrollably.

**Expected behavior**
Player name appears under supports if entered.

**Additional context**
May be related to delayed Mission Card up.

**Comment by jvanlint** [comment]
Player name added to mission card for support.
