### ISSUE TITLE
Take Slot button from /mission/## page leads to server error when not logged in.

### ISSUE THREAD

**Issue by Steveveepee** [jvanlint/OPTICS#30]
Clicking the take slot button on the mission sign up sheet when not logged in fails.

To be fair, the user cannot normally navigate to this page without signing in to the app, but if the page is posed in discord etc the page loads and looks like they can just sign up for a mission slot.

need a check for signed in user on the button and a re-direct to sign in page then back to the mission page.

**Comment by jvanlint** [comment]
Fair enough....thanks for also proposing a fix.

**Comment by jvanlint** [comment]
Is this still a concern Shrike?

**Comment by Steveveepee** [comment]
Looks like it now has a login_required decorator, so fixed.
