### ISSUE TITLE
Ability to add bulk aircraft to a flight and/or clone other flights

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#33]
**Describe the solution you'd like**
The ability to add X number of an airframe to a flight without having to add every single one. Ideally you set the criteria for the first aircraft and it clones it. Then you can tweak the detail of each aircraft.
This has become particularly relevant for Liberation where the packages are not known until quite late in the planning.

**Describe alternatives you've considered**

**Additional context**

**Comment by jvanlint** [comment]
Aircraft can be copied using the drop down action button.
