### ISSUE TITLE
Add ability to signup for second seat in multi crew aircraft in the Signup sheet

### ISSUE THREAD

**Issue by OLDrGoldleader** [jvanlint/OPTICS#34]
**Is your feature request related to a problem? Please describe.**
No problem per se...

**Describe the solution you'd like**
The ability to allocate yourself into a RIO slot via the signup sheet without having to deep dive into the package details and potentially change something you shouldn't Pilots can do it so why are the RIOs being discriminated against... ;)

**Comment by Steveveepee** [comment]
In order to appease the whingy failed pilot's in the back, and restore balance to the farce, I have slaved away on my sunday to bring this pitiful desire to its ultimate conclusion.

Don't break it you ham-fisted thugs :)
