### ISSUE TITLE
Have signup sheet apply package/flight lead tags and place them in that priority order.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#35]
**Is your feature request related to a problem? Please describe.**
Currently the Signup Sheet (eg [https://apps.deadfrogstudios.com/airops/mission/signup/19?returnUrl=/airops/mission/19/](url)) does not order aircraft in flights by command precedence or indicate what the pilot of that aircraft is in charge of this makes it challenging for players to choose how much responsibility they want.
Additionally, it appears to order them backwards so designated flight lead is at the bottom..

**Describe the solution you'd like**
Signup sheet displays flight/package lead under the bold text for the flight name (circled in red). order of aircraft places the flight containing Package lead at the top of the package list and flight lead airframes at the top of their flight.
![image](https://user-images.githubusercontent.com/40154322/124347975-a468c980-dc2a-11eb-9957-59cf83d5430f.png)

**Describe alternatives you've considered**
Abducting Tiger's family and forcing him to make this better.

**Comment by jvanlint** [comment]
Labels implemented as requested.
