### ISSUE TITLE
Lists do not present in alphabetical order

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#40]
**Describe the bug**
This needs to be in Alphabetical order (its a single list)
![image](https://user-images.githubusercontent.com/40154322/124876194-16ffed80-e00d-11eb-96c3-b9fd68fae7ec.png)

.. And so does this
![image](https://user-images.githubusercontent.com/40154322/124876336-3d258d80-e00d-11eb-8b90-b72c02b9b358.png)

**Comment by Steveveepee** [comment]
could we implement Click on column heading to sort?

**Comment by jvanlint** [comment]
Both pilot and airframe lists now present in alpha order.
