### ISSUE TITLE
Ability to duplicate threat/target/support entries

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#41]
**Is your feature request related to a problem? Please describe.**
Currently you need to re-create targets/threats/supports  from mission to mission OR drag them from one mission to another (which then wrecks the old mission's integrity as far as detail goes).

**Describe the solution you'd like**
The ability to 'Copy' a target/threat/support/flight/package into a new mission. At this time, it would be best if it flat out creates a new entry rather than assigning a single entry to two different missions.

![image](https://user-images.githubusercontent.com/40154322/124885793-fa68b300-e016-11eb-9411-d5f4a46d7497.png)

**Comment by jvanlint** [comment]
Targets, threats and supports can now be copied using the drop down button menu.
