### ISSUE TITLE
Make the signup button more prominent

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#42]
**Is your feature request related to a problem? Please describe.**
Currently the signup button is out of the way and not immediately apparent, particularly to new users.
![image](https://user-images.githubusercontent.com/40154322/124890675-9f858a80-e01b-11eb-983a-929725ae1e27.png)
_Where even is this?_

**Describe the solution you'd like**
It would be good to put the sign up button in more visible locations as a large green button:

![image](https://user-images.githubusercontent.com/40154322/124890918-db205480-e01b-11eb-9552-2189a163eca1.png)

_And Here:_

![image](https://user-images.githubusercontent.com/40154322/124891305-33575680-e01c-11eb-9200-370c241e3247.png)

**Describe alternatives you've considered**
Funding a national university to run a three year degree program to train users how to find the current sign-up button.

**Comment by jvanlint** [comment]
Button added to top right hand corner of mission page.
