### ISSUE TITLE
Add 'Airfield' to the support type list

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#43]
**Is your feature request related to a problem? Please describe.**
Pls add 'Airfield' to the support type list. Currently there is no clear place to put airbase freqs. Considering that anyone may need to land there, it isn't appropriate to put it in waypoints.
![image](https://user-images.githubusercontent.com/40154322/124924159-7c200700-e03e-11eb-8e21-7379a24574dd.png)

**Comment by jvanlint** [comment]
Airfield added as requested.
