### ISSUE TITLE
Need to update quickstart guide.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#44]
**Describe the bug**
Currently the quickstart guide does not incorporate the new 'sign up' feature. This needs to amended.

**Comment by Floydii** [comment]
Will wait on updated 'sign up' button implementation IOT take accurate screenshots. In the meantime will change to A4 portrait format PDF.

Related to issue #42 (Make the signup button more prominent).

**Comment by jvanlint** [comment]
Can I suggest we do this in the wiki attached to this repo?
I started it.....it also means anyone can update it and it will always reflect the current documentation.

**Comment by Floydii** [comment]
[Done.](https://github.com/jvanlint/OPTICS/wiki/Quick-Start-Guide-to-Using-O.P.T.I.C.S-for-Mission-Participants) Current at as 08/08/21.
