### ISSUE TITLE
Adding Package and Flight specific freetext fields in respective OPTICS areas.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#45]
**Is your feature request related to a problem? Please describe.**
Currently there is limited ability for Package/Flight leads to put planning or coord details into their respective pages. The Package screen has the 'Description of package objective' section, but this shows up on the mission page and becomes unwieldy if it is more than a sentence or two long. Flight screen has no ability for free text. 

**Describe the solution you'd like**
1. Rename the 'Description of package objective' to 'Summary of package objective'. This will continue to be shown on the mission page next to the Package name. on the package screen, this text will now also have a heading of ''Summary of package objective'
2. A freetext box called 'Package Coordination' will appear on the package screen underneath the ''Summary of package objective' text field. This should have no character limits and will allow the Package lead to discuss anything not covered elsewhere.

As a slight branch (and not essential at the moment), the ability for any user tagged as Package or flight lead in a given package should be able to edit these fields.

**Comment by jvanlint** [comment]
Package summary and coordination fields modified and added where appropriate,
