### ISSUE TITLE
Ability to sort campaigns by various criteria

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#56]
**Is your feature request related to a problem? Please describe.**
Currently, Campaigns on the [main page ](https://apps.deadfrogstudios.com/airops/campaign) appear to be sorted by the order they were created. This is not a significant issue at the moment, but as time goes on the list will become longer.. and consequently harder to navigate.

**Describe the solution you'd like**
an option at the top of the main OPTICS page to 'Sort Campaigns By' with the options being"

- Date Created (Oldest to Newest)
- Date Created (Newest to Oldest)
- Status (with Active always being at the top)
- Alphabetical order (A-Z)
- Next Scheduled Mission (so, whichever campaign has its next mission running soonest to current time).

**Describe alternatives you've considered**
Nil.

**Additional context**
Nil.

**Comment by jvanlint** [comment]
Implemented everything except the "upcoming" order. This is complex in that it involves querying every mission in every campaign to determine the campaign that has the closet event. It's an expensive operation and probably best left to upcoming "calendar" of missions.

**Comment by Steveveepee** [comment]
WRT a deep lookup to determine the upcoming order. How about when a mission is added, a hidden field for the latest mission date in that campaign is set at the campaign table level, Then the sort will be only 1 layer deep.

**Comment by Floydii** [comment]
This is not implemented in V2
