### ISSUE TITLE
mission card does not honour waypoint sequence

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#66]
**Describe the bug**
Per the images below, the Mission card does not respect the waypoint number. This is after changing the BAI waypoint multiple times and using Ctrl-F5 to force a refresh on the PDF.
![image](https://user-images.githubusercontent.com/40154322/129652490-5cc8c4bf-8948-40be-a78f-af2536255a4b.png)
![image](https://user-images.githubusercontent.com/40154322/129652529-7d39b37e-4162-4521-8142-6a6e4f78e340.png)

**Expected behavior**
The waypoints on a mission card should be presented in order of the waypoint number.

**Additional context**
Note that the Target/BAI waypoint was the first one created by the mission maker, so unsure if this is the culprit.

**Comment by jvanlint** [comment]
Order-by field added to waypoint object sent to mission card.
