### ISSUE TITLE
In-game mission date as reflected at top of mission page says 'midnight' regardless of actual time.

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#70]
**Describe the bug**
Per the image below the 'Mission Time' field in the Mission page will always say 'midnight'. This is potentially misleading to players and should be removed (unless you want to do coding to determine Night/Dawn/Day/Dusk timings year round for each theatre).
![image](https://user-images.githubusercontent.com/40154322/130526737-906b1d44-2a3b-4fe9-8800-41d8cd883b43.png)

**To Reproduce**
I note it is on all missions.

**Expected behavior**
Either this is set by the mission creator (after making an assessment of lighting conditions in the mission), or it is removed entirely. If a manual setting is adopted, not indicating 
 general time of day (Day/Night/Dawn etc) should mean nothing is written at all.

**Comment by jvanlint** [comment]
Fixed
