### ISSUE TITLE
Comments in v2 campaign screen show incorrect user avatars

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#73]
Per the image below, all users avatars in the comments section show the current viewer's avatar rather than those of the original message author. This affects mobile and desktop.

![20210913_115415](https://user-images.githubusercontent.com/40154322/133012886-05b3bfe5-c568-4d47-9c3d-ae71a4284668.jpg)

**Comment by jvanlint** [comment]
Fixed.
