### ISSUE TITLE
duplicate values in reference tables

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#78]
Is there a way to police when new values are added to reference tables? case in point is the image below where there are two instances of 'takeoff / take off'. I assume if one is deleted, then all missions using that value will see it removed. Potential solution is a question that requires the person deleting the value to specify a value to replace it (so when I delete 'take off' it replaces all instances with 'takeoff' after I specify that).

I am unsure what level of permission is required to add new values, but I would suggest it is set at Admin only.
![image](https://user-images.githubusercontent.com/40154322/133576880-2e9c2f23-0280-4cb4-9000-cfbd65608574.png)

**Comment by jvanlint** [comment]
Only admin types will be allowed to manipulate these values. This duplication is an error. Enforcing some kind of check is a little OTT.

**Comment by jvanlint** [comment]
I believe that addition of Takeoff was just a test and we will limit access to this screen in the future.
