### ISSUE TITLE
Easy method to sign up for missions

### ISSUE THREAD

**Issue by jvanlint** [jvanlint/OPTICS#8]
The tool needs a quick interface to allow players to place their names in an available slot. Should also include some basic info about package and flight to enable the player to select the appropriate slot based on their skill, airframe and mission preferences.

**Comment by Steveveepee** [comment]
This could be linked to a user account having a callsign field. Then just add a "take this slot" button that adds the user to the flight and populates the callsign field.
This could also be used by the owner of the campaign or the flight lead to contact the users signed up to a flight via future discord bot plugin etc.

**Comment by Floydii** [comment]
Ideally it shows data equivalent to the flight details in the kneeboard to give the player an idea of the tasks. It would also indicate who else has signed up for a particular slot as well.
