### ISSUE TITLE
Targets do not appear on the flight page when assigned to the flight

### ISSUE THREAD

**Issue by Floydii** [jvanlint/OPTICS#80]
Targets do not appear on the flight page when assigned to the flight. They can be selected in the flight edit mode, but it doesn't stick and doesn't show up on the flight page itself. Ctrl F5 does not fix this.

**Comment by Steveveepee** [comment]
v1 uses crispy forms for flight edit form, v2 uses generic_data_entry_form and not crispy.
In v2 the select control for the target field is not getting and setting the values correctly on GET or POST, with all options having the selected tag.

Suggest modifying the `v2/generic/data_entry_form.html` to use crispy forms.

**Comment by jvanlint** [comment]
Issue fixed by explicitly setting Target field value in when adding Targets.
